### Use Google Drive to Store Datasets

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
root_path = '/content/gdrive/My Drive/Colab Notebooks/Datasets/'
root_path

'/content/gdrive/My Drive/Colab Notebooks/Datasets/'

# Week 1

## Imports for Text Pre-Processing

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

Tokenization

In [0]:
#Tokenization

# word_counts: A dictionary of words and their counts.
# word_docs: A dictionary of words and how many documents each appeared in.
# word_index: A dictionary of words and their uniquely assigned integers.
# document_count:An integer count of the total number of documents that were used to fit the Tokenizer.


sentences = ['I Love my Dog.',
             'I Love my Cat.'
             ]

# Strip Punctuation, Capitalization, Exclamation
# Hyperparameter : num_words() ... The maximum number of words to keep, based on word frequency.
tokenizer = Tokenizer(num_words=100)

tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

print("Word Index\n", word_index)

Word Index
 {'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


Working with Sequences and ensuring each sentence is of the same Length

In [0]:
# Working with Sequences and ensuring each sentence is of the same Length

sentences = ['I Love my Dog.',
             'I Love my Cat.',
             'How much do you love your Dog?',
             'My Dog is really Amazing'
             ]

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(texts=sentences)

print("Word Index\n", word_index)
print("\nSequence\n", sequences)

Word Index
 {'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'how': 6, 'much': 7, 'do': 8, 'you': 9, 'your': 10, 'is': 11, 'really': 12, 'amazing': 13}

Sequence
 [[3, 1, 2, 4], [3, 1, 2, 5], [6, 7, 8, 9, 1, 10, 4], [2, 4, 11, 12, 13]]


In [0]:
# Out of Vocab Handling [Optional Section]

tokenizer = Tokenizer(num_words=100,oov_token="<00V>")

sentences = ['I Love my Dog.',
             'I Love my Cat.',
             ]

tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(texts=sentences)

print("Word Index\n", word_index)
print("\nSequence\n", sequences)

sentences = ['I Love my Dog.',
             'I Love my Cat.',
             'How much do you love your Dog?',
             'My Dog is really Amazing'
             ]

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(texts=sentences)

print("\nWord Index\n", word_index)
print("\nSequence\n", sequences)

Word Index
 {'<00V>': 1, 'i': 2, 'love': 3, 'my': 4, 'dog': 5, 'cat': 6}

Sequence
 [[2, 3, 4, 5], [2, 3, 4, 6]]

Word Index
 {'<00V>': 1, 'i': 2, 'love': 3, 'my': 4, 'dog': 5, 'cat': 6}

Sequence
 [[2, 3, 4, 5], [2, 3, 4, 6], [1, 1, 1, 1, 3, 1, 5], [4, 5, 1, 1, 1]]


In [0]:
#Padding in Sentences

from tensorflow.keras.preprocessing.sequence import pad_sequences


sentences = ['I Love my Dog.',
             'I Love my Cat.',
             'How much do you love your Dog?',
             'My Dog is really Amazing'
             ]

tokenizer = Tokenizer(num_words=100,oov_token="<00V>")

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)

# maxlen and truncating='post' can restrcit the sentence to a User Defined Length. The default truncate for maxlen is Pre hence Truncating can be used to control this.

padded = pad_sequences(sequences,padding='post',)

print("Word Index\n", word_index)
print("\nSequence\n", sequences)
print("\nPadded Sequence\n",padded)

Word Index
 {'<00V>': 1, 'love': 2, 'my': 3, 'dog': 4, 'i': 5, 'cat': 6, 'how': 7, 'much': 8, 'do': 9, 'you': 10, 'your': 11, 'is': 12, 'really': 13, 'amazing': 14}

Sequence
 [[5, 2, 3, 4], [5, 2, 3, 6], [7, 8, 9, 10, 2, 11, 4], [3, 4, 12, 13, 14]]

Padded Sequence
 [[ 5  2  3  4  0  0  0]
 [ 5  2  3  6  0  0  0]
 [ 7  8  9 10  2 11  4]
 [ 3  4 12 13 14  0  0]]


Dataset Setup

In [0]:
file_url = 'http://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json'

In [0]:
# Libraries to Import Data into Programming Perspective

import requests
import json

In [0]:
# Copy File from Public Source to Personal Google Drive

r = requests.get(file_url, stream = True)  
with open(root_path + "sarcasm.json", "wb") as file:  
    for block in r.iter_content(chunk_size = 2048): 
         if block:  
             file.write(block) 

In [0]:
  # Load File into a List for Parsing
  
  with open(root_path + "sarcasm.json","r") as file:
    datastore = json.load(file)

In [0]:
sentences = []
labels = []
urls =[]

for item in datastore:
  sentences.append(item['headline'])
  labels.append(item['is_sarcastic'])
  urls.append(item['article_link'])

In [0]:
tokenizer = Tokenizer(oov_token="<00V>")

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences,padding='post',)

In [0]:
print("Word Index\n", word_index)
print("\nSequence\n", sequences[0])
print("\nPadded Sequence\n",padded[0])

# We had 26,709 sentences, and they were encoded with padding, to get them up to 40 words long which was the length of the longest word.

print("\nShape of Padded Sequence.\n",padded.shape)


Word Index
 {'<00V>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'from': 15, 'at': 16, 'about': 17, 'you': 18, 'this': 19, 'by': 20, 'after': 21, 'up': 22, 'out': 23, 'be': 24, 'how': 25, 'as': 26, 'it': 27, 'that': 28, 'not': 29, 'are': 30, 'your': 31, 'his': 32, 'what': 33, 'he': 34, 'all': 35, 'just': 36, 'who': 37, 'has': 38, 'will': 39, 'more': 40, 'one': 41, 'into': 42, 'report': 43, 'year': 44, 'why': 45, 'have': 46, 'area': 47, 'over': 48, 'donald': 49, 'u': 50, 'day': 51, 'says': 52, 's': 53, 'can': 54, 'first': 55, 'woman': 56, 'time': 57, 'like': 58, 'her': 59, "trump's": 60, 'old': 61, 'no': 62, 'get': 63, 'off': 64, 'an': 65, 'life': 66, 'people': 67, 'obama': 68, 'now': 69, 'house': 70, 'still': 71, "'": 72, 'women': 73, 'make': 74, 'was': 75, 'than': 76, 'white': 77, 'back': 78, 'my': 79, 'i': 80, 'clinton': 81, 'down': 82, 'if': 83, '5': 84, 'when': 85, 'world': 86, 'could': 87, '

# Week 2

## Word Embeddings - Imparting Semantics to Vector Represenation of Words

In [0]:
print(tf.__version__)

1.15.0


In [0]:
tf.enable_eager_execution()

In [0]:
import tensorflow_datasets as tfds
import numpy as np

In [0]:
imdb,info = tfds.load("imdb_reviews",with_info=True,as_supervised=True)

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/0.1.0. Subsequent calls will reuse this data.


In [0]:
training_sentences = []
training_labels = []

testing_sentences = []
testing_labels = []

train_data, test_data = imdb['train'],imdb['test']

In [0]:
for s,l in train_data:
  training_sentences.append(str(s.numpy()))
  training_labels.append(l.numpy())


for s,l in test_data:
  testing_sentences.append(str(s.numpy()))
  testing_labels.append(l.numpy())

In [0]:
print("Number of Training Sentences = ",len(training_sentences))
print("Number of Training Labels = ",len(training_labels))

print("\n\nNumber of Testing Sentences = ",len(testing_sentences))
print("Number of Testing Labels = ",len(testing_labels))

Number of Training Sentences =  50000
Number of Training Labels =  50000


Number of Testing Sentences =  25000
Number of Testing Labels =  25000


In [0]:
training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

In [0]:
# Hyper Parameters

vocab_size = 10000
embedding_dim = 16
max_length = 120
trunc_type = 'post'
oov_tok = "<OOV>"

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:
tokenizer = Tokenizer(num_words= vocab_size, oov_token=oov_tok)

tokenizer.fit_on_texts(training_sentences)

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences,maxlen=max_length,truncating=trunc_type)

In [0]:
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length)

### Model Creation

In [0]:
model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(vocab_size,embedding_dim,input_length=max_length),
                             tf.keras.layers.GlobalAveragePooling1D(),
                             tf.keras.layers.Dense(6,activation='relu'),
                             tf.keras.layers.Dense(1,activation='sigmoid')
])

In [0]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 120, 16)           160000    
_________________________________________________________________
global_average_pooling1d_2 ( (None, 16)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 102       
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 7         
Total params: 160,109
Trainable params: 160,109
Non-trainable params: 0
_________________________________________________________________


In [0]:
num_epochs = 10
model.fit(padded, 
          training_labels_final, 
          epochs=num_epochs, 
          validation_data=(testing_padded, testing_labels_final)
)

Train on 50000 samples, validate on 25000 samples
Epoch 1/10
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


50000/50000 [==============================] - 11s 215us/sample - loss: 0.4346 - acc: 0.8166 - val_loss: 0.3353 - val_acc: 0.8545
Epoch 2/10
50000/50000 [==============================] - 10s 194us/sample - loss: 0.2494 - acc: 0.9021 - val_loss: 0.3491 - val_acc: 0.8524
Epoch 3/10
50000/50000 [==============================] - 10s 194us/sample - loss: 0.1951 - acc: 0.9283 - val_loss: 0.4024 - val_acc: 0.8399
Epoch 4/10
50000/50000 [==============================] - 10s 196us/sample - loss: 0.1601 - acc: 0.9438 - val_loss: 0.4546 - val_acc: 0.8324
Epoch 5/10
50000/50000 [==============================] - 10s 192us/sample - loss: 0.1341 - acc: 0.9556 - val_loss: 0.5282 - val_acc: 0.8225
Epoch 6/10
50000/50000 [==============================] - 10s 193us/sample - loss: 0.1127 - acc: 0.9647 - val_loss: 0.6283 - val_acc: 0.8142
Epoch 7/10
50000/50000 [==============================] - 10s 197us/sample - loss: 0.0947 - acc: 0.9721 - val_loss: 0.7022 - val_acc: 0.8138
Epoch 8/10
50000/50000 [

In [0]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(10000, 16)


### LSTMs

In [1]:
from pandas import Series
from sklearn.preprocessing import MinMaxScaler
# define contrived series
data = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]
series = Series(data)
print(series)
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))
# train the normalization
scaler = MinMaxScaler(feature_range=(0, 1))
scaler = scaler.fit(values)
print('Min: %f, Max: %f' % (scaler.data_min_, scaler.data_max_))
# normalize the dataset and print
normalized = scaler.transform(values)
print(normalized)
# inverse transform and print
inversed = scaler.inverse_transform(normalized)
print(inversed)

0     10.0
1     20.0
2     30.0
3     40.0
4     50.0
5     60.0
6     70.0
7     80.0
8     90.0
9    100.0
dtype: float64
Min: 10.000000, Max: 100.000000
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]
[[ 10.]
 [ 20.]
 [ 30.]
 [ 40.]
 [ 50.]
 [ 60.]
 [ 70.]
 [ 80.]
 [ 90.]
 [100.]]


In [2]:
from pandas import Series
from sklearn.preprocessing import StandardScaler
from math import sqrt
# define contrived series
data = [1.0, 5.5, 9.0, 2.6, 8.8, 3.0, 4.1, 7.9, 6.3]
series = Series(data)
print(series)
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))
# train the normalization
scaler = StandardScaler()
scaler = scaler.fit(values)
print('Mean: %f, StandardDeviation: %f' % (scaler.mean_, sqrt(scaler.var_)))
# normalize the dataset and print
standardized = scaler.transform(values)
print(standardized)
# inverse transform and print
inversed = scaler.inverse_transform(standardized)
print(inversed)

0    1.0
1    5.5
2    9.0
3    2.6
4    8.8
5    3.0
6    4.1
7    7.9
8    6.3
dtype: float64
Mean: 5.355556, StandardDeviation: 2.712568
[[-1.60569456]
 [ 0.05325007]
 [ 1.34354035]
 [-1.01584758]
 [ 1.26980948]
 [-0.86838584]
 [-0.46286604]
 [ 0.93802055]
 [ 0.34817357]]
[[1. ]
 [5.5]
 [9. ]
 [2.6]
 [8.8]
 [3. ]
 [4.1]
 [7.9]
 [6.3]]


In [4]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False, categories='auto')
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


In [6]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from numpy import array
from keras.models import load_model

Using TensorFlow backend.
